package Telas;

import Controlador.Empresa;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class TelaPrincipal extends javax.swing.JFrame {
 Empresa emp;
 
    public TelaPrincipal(Empresa emp) {
        initComponents();
        this.emp = emp;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        label1 = new java.awt.Label();
        popupMenu1 = new java.awt.PopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        botaoCadastrar = new javax.swing.JButton();
        botaoCarregarDados = new javax.swing.JButton();
        botaoSalvarDados = new javax.swing.JButton();
        botaoRegistrarCompra = new javax.swing.JButton();
        botaoRelatorios = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        label1.setText("label1");

        popupMenu1.setLabel("popupMenu1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(400, 200));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        botaoCadastrar.setText("Cadastrar");
        botaoCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCadastrarMouseClicked(evt);
            }
        });
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });

        botaoCarregarDados.setText("Carregar Dados");
        botaoCarregarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCarregarDadosActionPerformed(evt);
            }
        });

        botaoSalvarDados.setText("Salvar Dados");
        botaoSalvarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarDadosActionPerformed(evt);
            }
        });

        botaoRegistrarCompra.setText("Registrar Compra");
        botaoRegistrarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRegistrarCompraActionPerformed(evt);
            }
        });

        botaoRelatorios.setText("Relatórios");
        botaoRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRelatoriosActionPerformed(evt);
            }
        });

        botaoSair.setText("Exit");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel1.setText("MENU PRINCIPAL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoCarregarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(botaoCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoRelatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoSalvarDados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoRegistrarCompra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCadastrar)
                    .addComponent(botaoRegistrarCompra))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCarregarDados)
                    .addComponent(botaoSalvarDados))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoRelatorios)
                    .addComponent(botaoSair))
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCarregarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCarregarDadosActionPerformed
     try {
         Controlador.Empresa.carregar(this.emp);
         JOptionPane.showMessageDialog(null, "Dados Carregados!", "Sucesso", JOptionPane.WARNING_MESSAGE);
     } catch (IOException | ClassNotFoundException ex) {
         JOptionPane.showMessageDialog(null, "Dados não carragados, tente novamente!", "Erro", JOptionPane.ERROR_MESSAGE);
         Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
     }

    }//GEN-LAST:event_botaoCarregarDadosActionPerformed

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        //botao cadastrar pressionado

        Object[] opcoes = {"Clientes", "Produtos"};
        Object selectedValue; //
        selectedValue = JOptionPane.showInputDialog(null, "Selecione o que deseja cadastrar", "Opções",
                JOptionPane.INFORMATION_MESSAGE, null, opcoes, opcoes[0]);
        this.setEnabled(false);
        //   System.out.println(selectedValue);
        if (selectedValue == null) {
            this.setEnabled(true);
        } else if (selectedValue.equals("Clientes")) {
            TelaCadastroCliente telinhaCadastroCliente = new TelaCadastroCliente(this, emp);
            telinhaCadastroCliente.setVisible(true);
        } else if (selectedValue.equals("Produtos")) {
            TelaCadastroProdutos telinhaCadastroProduto = new TelaCadastroProdutos(this, emp);
            telinhaCadastroProduto.setVisible(true);
        }

    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void botaoCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCadastrarMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_botaoCadastrarMouseClicked

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botaoSairActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    private void botaoRegistrarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRegistrarCompraActionPerformed
        TelaCadastroVenda telinhaCadastroVenda = new TelaCadastroVenda(this.emp);
        telinhaCadastroVenda.setVisible(true);
    }//GEN-LAST:event_botaoRegistrarCompraActionPerformed

    private void botaoSalvarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarDadosActionPerformed
     try {
         Controlador.Empresa.salvar(this.emp);
         JOptionPane.showMessageDialog(null, "Dados foram salvos!", "Sucesso", JOptionPane.WARNING_MESSAGE);
     } catch (IOException ex) {
         JOptionPane.showMessageDialog(null, "Dados não foram salvos, tente novamente!", "Erro", JOptionPane.ERROR_MESSAGE);
         Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
     }
    }//GEN-LAST:event_botaoSalvarDadosActionPerformed

    private void botaoRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRelatoriosActionPerformed
       //botao cadastrar pressionado

        Object[] opcoes = {"Clientes",
                                          "Produtos",
                                          "Vendas"};
        Object selectedValue; //
        selectedValue = JOptionPane.showInputDialog(null, "Selecione o relatórios desejado", "Opções",
                JOptionPane.INFORMATION_MESSAGE, null, opcoes, opcoes[0]);
        this.setEnabled(false);
        //   System.out.println(selectedValue);
        if (selectedValue == null) {
            this.setEnabled(true);
        } else if (selectedValue.equals("Clientes")) {
            TelaRelatorioCliente telinhaRelatorioClientes = new TelaRelatorioCliente(this, emp);
            telinhaRelatorioClientes.setVisible(true);
        } else if (selectedValue.equals("Produtos")) {
            TelaRelatorioProduto telinhaRelatorioProdutos = new TelaRelatorioProduto(this, emp);
            telinhaRelatorioProdutos.setVisible(true);
        }
        else if (selectedValue.equals("Vendas")) {
            TelaRelatorioVendas telinhaRelatorioVendas = new TelaRelatorioVendas(this, emp);
            telinhaRelatorioVendas.setVisible(true);
        }
        else if (selectedValue.equals("Cliente Específico")) {
            TelaRelatorioClienteEspecifico telinhaRelatorioClienteEspecifico = new TelaRelatorioClienteEspecifico(this, emp);
            telinhaRelatorioClienteEspecifico.setVisible(true);
        }
    }//GEN-LAST:event_botaoRelatoriosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoCarregarDados;
    private javax.swing.JButton botaoRegistrarCompra;
    private javax.swing.JButton botaoRelatorios;
    private javax.swing.JButton botaoSair;
    private javax.swing.JButton botaoSalvarDados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private java.awt.Label label1;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
