package Telas;

import Controlador.Empresa;
import Controlador.Item;
import Controlador.TipoPagamento;
import Controlador.Venda;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TelaRelatorioVendas extends javax.swing.JFrame {

    TelaPrincipal telaAnterior;
    Empresa emp;

    public TelaRelatorioVendas(TelaPrincipal telaAnterior, Empresa emp) {
        initComponents();
        this.emp = emp;
        this.telaAnterior = telaAnterior;

        DefaultTableModel model = (DefaultTableModel) this.tableClientes.getModel();
        this.tableClientes.setModel(model);
        Float qtd = 0F;
        Venda[] vendas = emp.getVendas();
        if (vendas != null) {
            for (Venda ven : vendas) {
                qtd += ven.calcularTotal();
                model.addRow(new Object[]{ven.getCliente().getNome(),
                    ven.getCliente().getCpf(),
                    ven.getNumero(),
                    ven.getData(),
                    "R$ " + ven.calcularTotal(),
                    ven.getTipoPgto().getTipoPagamento()});
            }
            this.qtdVendas.setText(qtd.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableClientes = new javax.swing.JTable();
        qtdVendas = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tipoPgt = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cpfCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pesquisar = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel1.setText("RELATÓRIO DE VENDAS");

        tableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CLIENTE", "CPF", "NOTA FISCAL", "DATA", "TOTAL", "T.PAGAMENTO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableClientes.getTableHeader().setReorderingAllowed(false);
        tableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableClientes);
        if (tableClientes.getColumnModel().getColumnCount() > 0) {
            tableClientes.getColumnModel().getColumn(0).setResizable(false);
            tableClientes.getColumnModel().getColumn(1).setResizable(false);
            tableClientes.getColumnModel().getColumn(2).setResizable(false);
            tableClientes.getColumnModel().getColumn(3).setResizable(false);
            tableClientes.getColumnModel().getColumn(4).setResizable(false);
            tableClientes.getColumnModel().getColumn(5).setResizable(false);
        }

        qtdVendas.setText("    ");

        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Total: ");

        tipoPgt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Dinheiro", "Cheque", "Cartão" }));
        tipoPgt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipoPgtItemStateChanged(evt);
            }
        });

        jLabel3.setText("Tipo de Pagamento:");

        cpfCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cpfClienteFocusLost(evt);
            }
        });

        jLabel4.setText("CPF Cliente:");

        pesquisar.setText("Pesquisar");
        pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoPgt, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pesquisar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qtdVendas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(6, 6, 6))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoPgt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(pesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel2)
                    .addComponent(qtdVendas))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        telaAnterior.setVisible(true);
        telaAnterior.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tipoPgtItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipoPgtItemStateChanged

    }//GEN-LAST:event_tipoPgtItemStateChanged

    private void cpfClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpfClienteFocusLost

    }//GEN-LAST:event_cpfClienteFocusLost

    private void pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarActionPerformed
        String tipo = (String) this.tipoPgt.getSelectedItem();
        String cpf = this.cpfCliente.getText();
        boolean todos;
        todos = tipo.equals("Todos");

        DefaultTableModel model = (DefaultTableModel) this.tableClientes.getModel();
        this.tableClientes.setModel(model);
        model.setNumRows(0);

        Float qtd = 0F;
        Venda[] vendas = emp.getVendas();
        if (vendas != null) {
            for (Venda ven : vendas) {
                if (ven.getTipoPgto().getTipoPagamento().equals(tipo) || todos) {
                    if (!cpf.equals("")) {
                        if (!cpf.equals(ven.getCliente().getCpf())) {
                            continue;
                        }
                    }
                    qtd += ven.calcularTotal();
                    model.addRow(new Object[]{ven.getCliente().getNome(),
                        ven.getCliente().getCpf(),
                        ven.getNumero(),
                        ven.getData(),
                        "R$ " + ven.calcularTotal(),
                        ven.getTipoPgto().getTipoPagamento()});
                }
            }
            this.qtdVendas.setText(qtd.toString());
        }
    }//GEN-LAST:event_pesquisarActionPerformed

    private void tableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableClientesMouseClicked
        DefaultTableModel model = (DefaultTableModel) this.tableClientes.getModel();
        this.tableClientes.setModel(model);

        Venda v;
        v = Controlador.Venda.buscarCodigo(emp.getVendas(), (String) model.getValueAt(this.tableClientes.getSelectedRow(), 2));
        if (v != null) {
            String relatorio = "Nota Fiscal: \t" + v.getNumero();
            relatorio+="\nData: \t" + v.getData();
            relatorio+="\n\nCliente: \t" + v.getCliente().getNome();
            relatorio+="\nCPF: \t" + v.getCliente().getCpf();
            relatorio+="\n\nProduto:";
            for (Item item : v.getItens()) {
                relatorio+="\n \t\t#" + item.getProduto().getCodigo() + " - " + item.getProduto().getDescricao() + "(" + item.getQuantidade()+ ") - R$ " + item.calcularTotal();
            }
            relatorio+="\n\nPagamento: \t" + v.getTipoPgto().exibirDados();
            relatorio+="\n\nTotal: \tR$" + v.calcularTotal();
            JOptionPane.showMessageDialog(null, relatorio, "Venda", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_tableClientesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRelatorioVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cpfCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pesquisar;
    private javax.swing.JLabel qtdVendas;
    private javax.swing.JTable tableClientes;
    private javax.swing.JComboBox<String> tipoPgt;
    // End of variables declaration//GEN-END:variables
}
